version: "{build}"
environment:
  GOPATH: c:\gopath
  GOVERSION: 1.11
  GO111MODULE: on
init:
  - git config --global core.autocrlf input
install:
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
  - set Path=c:\go\bin;c:\gopath\bin;C:\Program Files (x86)\Bazaar\;C:\Program Files\Mercurial\%Path%
  - go version
build: false
deploy: false
test_script:
  - go test .
